insert into book (author, price, published_year, title) values ('Lolita Squibbes', 3, 87, 'pretium');
insert into book (author, price, published_year, title) values ('Karlotta Garmons', 32, 91, 'donec odio');
insert into book (author, price, published_year, title) values ('Madelene Kelwaybamber', 87, 21, 'odio consequat varius');
insert into book (author, price, published_year, title) values ('Alessandra Brittoner', 96, 21, 'curabitur convallis duis consequat');
insert into book (author, price, published_year, title) values ('Baryram McFetridge', 75, 45, 'orci vehicula');
insert into book (author, price, published_year, title) values ('Selma Larmour', 12, 27, 'id nisl venenatis');
insert into book (author, price, published_year, title) values ('Cathi Barnett', 34, 71, 'ipsum ac tellus');
insert into book (author, price, published_year, title) values ('Helena Holde', 86, 38, 'et magnis dis');
insert into book (author, price, published_year, title) values ('Meridith Johns', 97, 27, 'diam neque');
insert into book (author, price, published_year, title) values ('Marin Gullivent', 25, 56, 'proin risus praesent');
insert into book (author, price, published_year, title) values ('Brenna Inch', 48, 24, 'neque aenean auctor gravida');
insert into book (author, price, published_year, title) values ('Anna-maria Meriel', 37, 81, 'quam sollicitudin vitae');
insert into book (author, price, published_year, title) values ('Hermina Songer', 34, 13, 'fusce');
insert into book (author, price, published_year, title) values ('Hollyanne Braidwood', 83, 98, 'curabitur convallis duis');
insert into book (author, price, published_year, title) values ('Curtis Sango', 98, 59, 'etiam vel augue');
insert into book (author, price, published_year, title) values ('Oliver Burkill', 65, 23, 'magna vulputate');
insert into book (author, price, published_year, title) values ('Sauveur Zannotti', 19, 20, 'sit amet nunc viverra');
insert into book (author, price, published_year, title) values ('Ben Gehringer', 38, 70, 'integer');
insert into book (author, price, published_year, title) values ('Irvine Reason', 36, 95, 'montes nascetur ridiculus mus');
insert into book (author, price, published_year, title) values ('Karlen Alldread', 46, 71, 'eu');
insert into book (author, price, published_year, title) values ('Renell McCaster', 54, 17, 'vestibulum sagittis sapien');
insert into book (author, price, published_year, title) values ('Skell Loughren', 82, 94, 'odio justo sollicitudin ut');
insert into book (author, price, published_year, title) values ('Tibold Delacroix', 68, 9, 'maecenas tristique');
insert into book (author, price, published_year, title) values ('Winfield Illsley', 15, 45, 'consequat');
insert into book (author, price, published_year, title) values ('Erik Capron', 46, 44, 'consectetuer');
insert into book (author, price, published_year, title) values ('Devi Cammiemile', 3, 14, 'ultrices enim lorem');
insert into book (author, price, published_year, title) values ('Brianna Fearnley', 70, 98, 'dolor quis odio consequat');
insert into book (author, price, published_year, title) values ('Winny Masding', 21, 56, 'integer ac leo pellentesque');
insert into book (author, price, published_year, title) values ('Sunshine Renton', 86, 84, 'potenti');
insert into book (author, price, published_year, title) values ('Fancie Torel', 35, 54, 'et ultrices');
insert into book (author, price, published_year, title) values ('Leoine Sissot', 66, 14, 'tellus in sagittis');
insert into book (author, price, published_year, title) values ('Miquela Huegett', 74, 25, 'nonummy');
insert into book (author, price, published_year, title) values ('Corny Swinfon', 66, 52, 'feugiat');
insert into book (author, price, published_year, title) values ('Ruthi Domenge', 98, 82, 'semper sapien');
insert into book (author, price, published_year, title) values ('Alexia Dewett', 22, 42, 'nulla pede ullamcorper');
insert into book (author, price, published_year, title) values ('Lorene Todarini', 82, 26, 'fusce consequat nulla');
insert into book (author, price, published_year, title) values ('Danell Furniss', 91, 19, 'morbi non');
insert into book (author, price, published_year, title) values ('Marcy Callingham', 78, 78, 'duis aliquam convallis');
insert into book (author, price, published_year, title) values ('Chadwick Callaway', 55, 97, 'et ultrices posuere');
insert into book (author, price, published_year, title) values ('Alta Sleany', 26, 16, 'sit amet');
insert into book (author, price, published_year, title) values ('Tull Carn', 47, 54, 'nulla facilisi');
insert into book (author, price, published_year, title) values ('Had Birds', 77, 73, 'curae duis faucibus');
insert into book (author, price, published_year, title) values ('Bart Andryunin', 73, 6, 'nulla suscipit ligula');
insert into book (author, price, published_year, title) values ('Molly Worwood', 53, 99, 'placerat');
insert into book (author, price, published_year, title) values ('Jonell Massy', 55, 8, 'elit sodales scelerisque mauris');
insert into book (author, price, published_year, title) values ('Lissie Owbridge', 60, 24, 'mauris sit amet eros');
insert into book (author, price, published_year, title) values ('Harbert Bankes', 74, 57, 'magna bibendum imperdiet nullam');
insert into book (author, price, published_year, title) values ('Jillana Hazleton', 96, 26, 'congue risus semper porta');
insert into book (author, price, published_year, title) values ('Gabie Markie', 45, 62, 'nonummy integer non');
insert into book (author, price, published_year, title) values ('Bartel Farnham', 6, 6, 'enim lorem ipsum dolor');
insert into book (author, price, published_year, title) values ('Moses Begwell', 26, 53, 'aenean');
insert into book (author, price, published_year, title) values ('Felicdad Boydell', 58, 28, 'posuere metus');
insert into book (author, price, published_year, title) values ('Wilek Elt', 54, 17, 'odio elementum eu');
insert into book (author, price, published_year, title) values ('Nap Genese', 18, 70, 'nulla eget eros');
insert into book (author, price, published_year, title) values ('Clarice Dellenbach', 33, 79, 'lobortis ligula sit');
insert into book (author, price, published_year, title) values ('Bron Mapston', 32, 76, 'est');
insert into book (author, price, published_year, title) values ('Verge Ishchenko', 59, 84, 'ipsum primis in');
insert into book (author, price, published_year, title) values ('Nanon Breffitt', 46, 97, 'nunc rhoncus dui vel');
insert into book (author, price, published_year, title) values ('Abigael Greenstead', 28, 68, 'in est risus auctor');
insert into book (author, price, published_year, title) values ('Gib Lutwidge', 1, 4, 'ac enim in tempor');
insert into book (author, price, published_year, title) values ('Tony Grushin', 33, 56, 'turpis');
insert into book (author, price, published_year, title) values ('Austen Poile', 30, 48, 'arcu sed');
insert into book (author, price, published_year, title) values ('Orlan Mirfield', 1, 41, 'molestie lorem');
insert into book (author, price, published_year, title) values ('Stanislaw Danilovitch', 99, 63, 'in tempus');
insert into book (author, price, published_year, title) values ('Candide Mora', 87, 92, 'pellentesque');
insert into book (author, price, published_year, title) values ('Millisent Feuell', 56, 52, 'enim');
insert into book (author, price, published_year, title) values ('Clotilda Eustes', 78, 64, 'vitae ipsum aliquam');
insert into book (author, price, published_year, title) values ('Kattie Salla', 14, 67, 'lacus morbi');
insert into book (author, price, published_year, title) values ('Massimiliano Mateo', 44, 6, 'est risus auctor');
insert into book (author, price, published_year, title) values ('Danny Fairebrother', 74, 96, 'amet erat nulla');
insert into book (author, price, published_year, title) values ('Alfredo Aslett', 86, 94, 'ac lobortis vel dapibus');
insert into book (author, price, published_year, title) values ('Alisa Sanbrooke', 70, 63, 'vivamus in');
insert into book (author, price, published_year, title) values ('Portie Walder', 51, 25, 'dui proin leo odio');
insert into book (author, price, published_year, title) values ('Alonzo Shields', 25, 75, 'eu magna vulputate');
insert into book (author, price, published_year, title) values ('Duff Goldwater', 24, 89, 'eget');
insert into book (author, price, published_year, title) values ('Maryanna Grigor', 94, 26, 'id nisl venenatis lacinia');
insert into book (author, price, published_year, title) values ('Mellisent Jacobowitz', 28, 34, 'tortor risus');
insert into book (author, price, published_year, title) values ('Ervin Pegrum', 30, 43, 'montes nascetur ridiculus');
insert into book (author, price, published_year, title) values ('Damiano Hansen', 97, 50, 'pellentesque at nulla');
insert into book (author, price, published_year, title) values ('Jacynth Malia', 90, 23, 'cras non velit nec');
insert into book (author, price, published_year, title) values ('Gene Ohms', 83, 33, 'urna');
insert into book (author, price, published_year, title) values ('Jany Wyche', 23, 32, 'ligula pellentesque ultrices');
insert into book (author, price, published_year, title) values ('Huntley Scheu', 10, 98, 'dolor');
insert into book (author, price, published_year, title) values ('Amelina Adamo', 51, 4, 'semper rutrum nulla');
insert into book (author, price, published_year, title) values ('Ammamaria Duxbury', 89, 88, 'at feugiat');
insert into book (author, price, published_year, title) values ('Theo Nealey', 87, 16, 'tempus semper');
insert into book (author, price, published_year, title) values ('Walliw McFfaden', 60, 22, 'natoque penatibus');
insert into book (author, price, published_year, title) values ('Fidel Wardell', 49, 11, 'volutpat eleifend');
insert into book (author, price, published_year, title) values ('Jacquenette Mechi', 41, 93, 'tempor');
insert into book (author, price, published_year, title) values ('Garald Chesshyre', 100, 96, 'pulvinar nulla pede');
insert into book (author, price, published_year, title) values ('Valerie Lillicrop', 75, 83, 'ac nulla sed');
insert into book (author, price, published_year, title) values ('Galen Brew', 31, 63, 'duis');
insert into book (author, price, published_year, title) values ('Evangeline Foystone', 88, 46, 'natoque');
insert into book (author, price, published_year, title) values ('Mar Trinder', 7, 62, 'purus sit amet nulla');
insert into book (author, price, published_year, title) values ('Caressa Hacksby', 20, 81, 'vestibulum vestibulum ante');
insert into book (author, price, published_year, title) values ('Guillermo Fantonetti', 52, 98, 'tortor id nulla');
insert into book (author, price, published_year, title) values ('Millicent Whorlton', 45, 1, 'sed tristique');
insert into book (author, price, published_year, title) values ('Ranice Chantler', 46, 14, 'quis odio');
insert into book (author, price, published_year, title) values ('Liane Zolini', 56, 97, 'leo pellentesque');
insert into book (author, price, published_year, title) values ('Natasha Teanby', 59, 49, 'mi in');
